FROM node:alpine as build
WORKDIR /app
COPY . .

ARG REACT_APP_API_URL
ARG REACT_APP_OAUTH_CLIENT_ID
ARG REACT_APP_OAUTH_CLIENT_SECRET
ARG REACT_APP_NOTIFICATION_URL

ENV REACT_APP_API_URL=${REACT_APP_API_URL}
ENV REACT_APP_OAUTH_CLIENT_ID=${REACT_APP_OAUTH_CLIENT_ID}
ENV REACT_APP_OAUTH_CLIENT_SECRET=${REACT_APP_OAUTH_CLIENT_SECRET}
ENV REACT_APP_NOTIFICATION_URL=${REACT_APP_NOTIFICATION_URL}

RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
ENTRYPOINT ["nginx","-g","daemon off;"]