# BUILD: docker build -t nexus.vn-dev.com/portal-vimc-fe-prod .
# REMOVE IMG OLD: docker image prune -f
# PUSH: docker push nexus.vn-dev.com/portal-vimc-fe-prod

version: '3.7'
services:
  portal-vimc-fe-prod:
    container_name: portal-vimc-fe-prod
    hostname: portal-vimc-fe-prod
    image: nexus.vn-dev.com/portal-vimc-fe-prod
    restart: always
    networks:
      - vimc-net
    ports:
      - '80:80'

networks:
  vimc-net:
    external: true